/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pggyqrqgyoehftdmnswa"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnZ3lxcnFneW9laGZ0ZG1uc3dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NzczNzMsImV4cCI6MjA3MjU1MzM3M30.M-nQHeg3vVytbP7T6zEwv2vvUITPmyqv6W2AcmPP2lU"

// Cloudflare Worker proxy URL
export const proxyUrl = "https://shiny-hill-82e1.abdullahrafique9783.workers.dev"

// Use proxy if direct Supabase connection is blocked
// Set to true to use proxy, false to use direct Supabase URL
export const useProxy = true

// Get the base URL based on proxy setting
export const getBaseUrl = () => {
  if (useProxy) {
    return proxyUrl;
  }
  return `https://${projectId}.supabase.co`;
}
